/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_FPOS_POS_H__)
#define __HAVE_FPOS_POS_H__


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS_POS
#define HAVE_FPOS_POS 1  /* yes */

#undef FPOS_POS_BITS
#undef FPOS_POS_LEN
#define FPOS_POS_BITS 32
#define FPOS_POS_LEN 4


#endif /* !__HAVE_FPOS_POS_H__ */
